/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Izza
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kerajaanhindu = new javax.swing.JButton();
        kerajaanislam = new javax.swing.JButton();
        kerajaanbudha = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        kerajaanhindu.setBackground(new java.awt.Color(204, 204, 204));
        kerajaanhindu.setText("Kerajaan Hindu");
        kerajaanhindu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerajaanhinduActionPerformed(evt);
            }
        });
        getContentPane().add(kerajaanhindu);
        kerajaanhindu.setBounds(30, 260, 130, 90);

        kerajaanislam.setBackground(new java.awt.Color(204, 204, 204));
        kerajaanislam.setText("Kerajaan Islam");
        kerajaanislam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerajaanislamActionPerformed(evt);
            }
        });
        getContentPane().add(kerajaanislam);
        kerajaanislam.setBounds(480, 260, 130, 90);

        kerajaanbudha.setBackground(new java.awt.Color(204, 204, 204));
        kerajaanbudha.setText("Kerajaan Budha");
        kerajaanbudha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerajaanbudhaActionPerformed(evt);
            }
        });
        getContentPane().add(kerajaanbudha);
        kerajaanbudha.setBounds(260, 260, 130, 90);

        jLabel3.setBackground(new java.awt.Color(102, 255, 153));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kerajaan Kerajaan ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 20, 430, 110);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 430, 70);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Di Indonesia");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(20, 140, 290, 78);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Izza\\Downloads\\hindu.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-7, 0, 640, 390);

        setBounds(0, 0, 646, 428);
    }// </editor-fold>//GEN-END:initComponents

    private void kerajaanhinduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerajaanhinduActionPerformed
        kerajaan_hindu a = new kerajaan_hindu();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_kerajaanhinduActionPerformed

    private void kerajaanbudhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerajaanbudhaActionPerformed
        kerajaan_budha a = new kerajaan_budha();
        a.setVisible(true);
        dispose();
    }//GEN-LAST:event_kerajaanbudhaActionPerformed

    private void kerajaanislamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerajaanislamActionPerformed
       kerajaan_islam a = new kerajaan_islam();
       a.setVisible(true);
       dispose();
    }//GEN-LAST:event_kerajaanislamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton kerajaanbudha;
    private javax.swing.JButton kerajaanhindu;
    private javax.swing.JButton kerajaanislam;
    // End of variables declaration//GEN-END:variables
}
